# Generated by Django 5.1.5 on 2025-01-28 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0006_alter_productmedia_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="is_selected",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="station",
        ),
        migrations.RemoveField(
            model_name="station",
            name="screen_name",
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "mp4", "mov"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="selected_media",
            field=models.ManyToManyField(
                blank=True, related_name="stations", to="screen_app.productmedia"
            ),
        ),
        migrations.DeleteModel(
            name="Linewise",
        ),
    ]
