# Generated by Django 5.1.5 on 2025-01-28 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0007_remove_productmedia_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                default=15,
                help_text="Duration in seconds (for all media types)",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "mp4", "mov", "xlsx", "xls"]
                    )
                ],
            ),
        ),
    ]
