# Generated by Django 5.1.5 on 2025-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0008_alter_productmedia_duration_alter_productmedia_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="pdf_version",
            field=models.FileField(
                blank=True, null=True, upload_to="product_media/pdf_versions/"
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=15, help_text="Duration in seconds"
            ),
        ),
    ]
