# Generated by Django 5.1.5 on 2025-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0009_productmedia_pdf_version_alter_productmedia_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
    ]
