# Generated by Django 5.1.5 on 2025-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0010_alter_productmedia_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="pdf_version",
        ),
        migrations.AddField(
            model_name="productmedia",
            name="image_version",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_media/image_versions/"
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=15, help_text="Duration in seconds"
            ),
        ),
    ]
