# Generated by Django 5.1.5 on 2025-01-28 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0011_remove_productmedia_pdf_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "Operator"),
                            ("TEAM_LEADER", "Team Leader"),
                            ("SHIFT_SUPERVISOR", "Shift Supervisor"),
                            ("QUALITY_SUPERVISOR", "Quality Supervisor"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A Shift"), ("B", "B Shift"), ("C", "C Shift")],
                        max_length=1,
                    ),
                ),
                ("line", models.CharField(max_length=50)),
                ("dvis_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delphi_part", models.CharField(max_length=20, unique=True)),
                ("model", models.CharField(max_length=50)),
                ("customer_part", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ConcernReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concern_identified", models.TextField()),
                ("cause", models.TextField(blank=True)),
                ("action_taken", models.TextField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturing_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturing_approvals",
                        to="screen_app.employee",
                    ),
                ),
                (
                    "quality_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_approvals",
                        to="screen_app.employee",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.inspectionsheet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspectionsheet",
            name="part_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="screen_app.partnumber"
            ),
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.IntegerField(
                        choices=[
                            (1, "Group 1"),
                            (2, "Group 2"),
                            (3, "Group 3"),
                            (4, "Group 4"),
                        ]
                    ),
                ),
                ("record_time", models.TimeField()),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.inspectionsheet",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operated_subgroups",
                        to="screen_app.employee",
                    ),
                ),
                (
                    "quality_supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_checked_subgroups",
                        to="screen_app.employee",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervised_subgroups",
                        to="screen_app.employee",
                    ),
                ),
                (
                    "team_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_subgroups",
                        to="screen_app.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("inspection", "group_number")},
            },
        ),
        migrations.CreateModel(
            name="MeasurementSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "program_selection",
                    models.CharField(
                        choices=[
                            ("P703", "P703"),
                            ("U704", "U704"),
                            ("FD", "FD"),
                            ("SA", "SA"),
                            ("Gnome", "Gnome"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "line_pressure",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(4.5),
                            django.core.validators.MaxValueValidator(5.5),
                        ],
                    ),
                ),
                (
                    "oring_condition",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "uv_flow_test_pressure",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(11),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                (
                    "uv_vacuum_test",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(-43),
                            django.core.validators.MaxValueValidator(-35),
                        ],
                    ),
                ),
                (
                    "uv_flow_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "lvdt_verification",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "master_verification",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "vacuum_test_pressure",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.25),
                            django.core.validators.MaxValueValidator(0.3),
                        ],
                    ),
                ),
                (
                    "tool_alignment",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                ("top_tool_id", models.CharField(max_length=50)),
                ("bottom_tool_id", models.CharField(max_length=50)),
                ("uv_assy_stage_id", models.CharField(max_length=50)),
                ("retainer_part_number", models.CharField(max_length=50)),
                ("uv_clip_part_number", models.CharField(max_length=50)),
                ("umbrella_part_number", models.CharField(max_length=50)),
                (
                    "retainer_lubrication",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "uv_clip_pressing",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "workstation_clean",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                (
                    "error_proofing_verified",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                (
                    "contamination_free",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.subgroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("subgroup", "sample_number")},
            },
        ),
    ]
