# Generated by Django 5.1.5 on 2025-01-28 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0012_employee_inspectionsheet_partnumber_concernreport_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurementsample",
            options={"ordering": ["sample_number"]},
        ),
        migrations.RemoveField(
            model_name="measurementsample",
            name="retainer_lubrication",
        ),
        migrations.RemoveField(
            model_name="measurementsample",
            name="tool_alignment",
        ),
        migrations.RemoveField(
            model_name="measurementsample",
            name="umbrella_part_number",
        ),
        migrations.RemoveField(
            model_name="measurementsample",
            name="uv_clip_part_number",
        ),
        migrations.RemoveField(
            model_name="measurementsample",
            name="uv_clip_pressing",
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="bottom_tool_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T05", "FMA-03-35-T05 (P703/U704/SA/FD/Gnome)"),
                    ("FMA-03-35-T06", "FMA-03-35-T06 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T08", "FMA-03-35-T08 (Gnome)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="line_pressure",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Line pressure (4.5 - 5.5 bar)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(4.5),
                    django.core.validators.MaxValueValidator(5.5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="program_selection",
            field=models.CharField(
                choices=[
                    ("P703", "P703"),
                    ("U704", "U704"),
                    ("FD", "FD"),
                    ("SA", "SA"),
                    ("Gnome", "Gnome"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="retainer_part_number",
            field=models.CharField(
                choices=[
                    ("42001878", "42001878 (P703/U704/SA/FD)"),
                    ("42050758", "42050758 (Gnome)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="top_tool_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T05", "FMA-03-35-T05 (P703/U704/SA/FD/Gnome)"),
                    ("FMA-03-35-T06", "FMA-03-35-T06 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T08", "FMA-03-35-T08 (Gnome)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="uv_assy_stage_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T07", "FMA-03-35-T07 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T09", "FMA-03-35-T09 (Gnome)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="uv_flow_test_pressure",
            field=models.DecimalField(
                decimal_places=2,
                help_text="UV Flow input Test Pressure (11-15 kPA)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(11),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="uv_flow_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="UV Flow Value (30~40 LPM)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="uv_vacuum_test",
            field=models.DecimalField(
                decimal_places=2,
                help_text="UV Vacuum Test range (-35 to -43 KPa)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(-43),
                    django.core.validators.MaxValueValidator(-35),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="vacuum_test_pressure",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Test Pressure for Vacuum generation (0.25 ~ 0.3 Mpa)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.25),
                    django.core.validators.MaxValueValidator(0.3),
                ],
            ),
        ),
    ]
