# Generated by Django 5.1.5 on 2025-01-28 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0013_alter_measurementsample_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="record_time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
