# Generated by Django 5.1.5 on 2025-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0014_alter_subgroup_record_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementsample",
            name="retainer_lubrication",
            field=models.CharField(
                choices=[("OK", "OK"), ("NG", "NG")],
                default="OK",
                help_text="Retainer ID lubrication status",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="measurementsample",
            name="umbrella_part_number",
            field=models.CharField(
                choices=[("25094588", "25094588 (P703/U704/SA/FD/Gnome)")],
                default="25094588",
                help_text="Select Umbrella Part Number",
                max_length=90,
            ),
        ),
        migrations.AddField(
            model_name="measurementsample",
            name="uv_clip_part_number",
            field=models.CharField(
                choices=[
                    ("42000829", "42000829 (P703/U704/SA/FD)"),
                    ("42000829", "42000829 (Gnome)"),
                ],
                default="42000829",
                help_text="Select UV Clip Part Number",
                max_length=90,
            ),
        ),
        migrations.AddField(
            model_name="measurementsample",
            name="uv_clip_pressing",
            field=models.CharField(
                choices=[("OK", "OK"), ("NG", "NG")],
                default="OK",
                help_text="UV Clip pressing status",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="bottom_tool_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T05", "FMA-03-35-T05 (P703/U704/SA/FD/Gnome)"),
                    ("FMA-03-35-T06", "FMA-03-35-T06 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T08", "FMA-03-35-T08 (Gnome)"),
                ],
                help_text="Select Bottom Tool ID",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="retainer_part_number",
            field=models.CharField(
                choices=[
                    ("42001878", "42001878 (P703/U704/SA/FD)"),
                    ("42050758", "42050758 (Gnome)"),
                ],
                help_text="Select Retainer Part Number",
                max_length=90,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="top_tool_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T05", "FMA-03-35-T05 (P703/U704/SA/FD/Gnome)"),
                    ("FMA-03-35-T06", "FMA-03-35-T06 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T08", "FMA-03-35-T08 (Gnome)"),
                ],
                help_text="Select Top Tool ID",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="measurementsample",
            name="uv_assy_stage_id",
            field=models.CharField(
                choices=[
                    ("FMA-03-35-T07", "FMA-03-35-T07 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T09", "FMA-03-35-T09 (Gnome)"),
                ],
                help_text="Select UV Assembly Stage ID",
                max_length=80,
            ),
        ),
    ]
