# Generated by Django 5.1.5 on 2025-01-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0015_measurementsample_retainer_lubrication_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="image_version",
        ),
    ]
