# Generated by Django 5.1.5 on 2025-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0017_productmedia_pdf_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectionsheet",
            options={"ordering": ["-document_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="inspectionsheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("complete", "Complete"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the inspection",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspectionsheet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="inspectionsheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name="inspectionsheet",
            index=models.Index(
                fields=["document_date", "shift"], name="screen_app__documen_665c37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsheet",
            index=models.Index(fields=["status"], name="screen_app__status_cb2e72_idx"),
        ),
    ]
