# Generated by Django 5.1.5 on 2025-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0018_alter_inspectionsheet_options_inspectionsheet_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionsheet",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="inspectionsheet",
            name="inspection_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="inspectionsheet",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
