# Generated by Django 5.1.5 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0019_remove_inspectionsheet_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionsheet",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="inspectionsheet",
            name="inspection_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
